### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by neurolabusc** [ReproNim/module-dataprocessing#37]
The paragraph [Machine accesibility means...](https://raw.githubusercontent.com/ReproNim/module-dataprocessing/3991d4baddb5e847be45df3082d59190747471e5/_episodes/02-concepts.md) has some odd formatting that appears when loaded with a [web browser](http://www.repronim.org/module-dataprocessing/02-concepts/), specifically '>' symbols and `{: .callout}`

**Comment by satra** [comment]
fixed via #36
